#!bin/bash

# SERVER IP BLACKLISTER
# Author: Alexia Rivera Steinberg
# http://www.github.com/alexiarstein
# -----------------------------------
# Usage (as root)
# chmod a+x blacklist.sh
# run (or cron) blacklist.sh
# ES: Para sacarle mayor provecho se debe agregar a un cronjob de 5 minutos.
# EN: To take full advantage of this script it's recommended to run it as a cronjob every 5 minutes.
# ----------------------------------
# reglas se agregan en /etc/firewalld

tail /var/log/secure | grep "Failed password for root" | awk '{print $11}' > /tmp/failedaccess.log
tail /var/log/secure | grep "Failed password for invalid user" | awk '{print $13}' >> /tmp/failedaccess.log
cat -n /tmp/failedaccess.log | sort -uk2 | sort -nk1 | cut -f2- > /tmp/failed.log
for failedLoginIP in $(cat /tmp/failed.log);
 do
firewall-cmd --permanent --add-rich-rule="rule family='ipv4' source address='$failedLoginIP' reject"
firewall-cmd --reload;
done

